### ISSUE TITLE
Cannot open t64 or d64

### ISSUE THREAD

**Issue by ecstaticax** [Spider-Lab/C64#2]
If I try to import a t64 o d64 that I saved on iCloud, when I click on the “+” icon, it open files. but I cannot select any d64 or t64. 
I can import exporting the file, from files, but opens on inbox.  Btw, you app is GREAT. Thanks.

**Comment by dillof** [comment]
I can reproduce the issue, i‘ll Look into it.

**Comment by ecstaticax** [comment]
I also tried to add or remove to extension, but on files, all C64 images are grey and cannot be imported. Your app is truly the best C64 emulator on iOS.
I also would like to know how to import the JiffyDOS roms (do they need a particular name?). I tried to import one (the C64 rom) but I cannot select it inside the settings. Regards and thanks.

**Comment by dillof** [comment]
Do you have any other Apps installed that handle D64 files? If so, which? I just committed a fix for when C64 Scene Browser is installed.

JiffyDOS: You have to drag them to the appropriate place in the settings screen (either from the Inbox, or from another app such as Files).

**Comment by ecstaticax** [comment]
I had 64.emu, the 64 emulator (taken from GitHub and based on C64 scene browser) and retroarch with 64 module. I deleted them all:  now I can select files on Files App, but they don’t get imported. Also another problem: when I create an entry from Inbox, selecting a file image, nothing happens. 

Good for JiffyDOS: it works. Now how can enable or disable it?

**Comment by kyelewis** [comment]
@dillof Out of curiosity, is this app still being actively developed?

The Library directory in Application Support doesn't exist by default, so the createDirectory fails creating the new Game.

Making withIntermediateDirectories: true on Game.swift Line 304 fixes this issue, and I'd see no reason not to keep this true, the libraryURL doesn't exist on a new installation and needs to be created.

Is it supposed to be created elsewhere perhaps?

**Comment by dillof** [comment]
Hi,

> On 11.04.2020, at 04:09, Kye Lewis <notifications@github.com> wrote:
> 
> 
> @dillof <https://github.com/dillof> Out of curiosity, is this app still being actively developed?
> 
It is still being developed, although not very actively at the moment. I still have big plans for it, though. Any help is very welcome.

> The Library directory in Application Support doesn't exist by default, so the createDirectory fails creating the new Game.
> 
> Making withIntermediateDirectories: true on Game.swift Line 304 fixes this issue, and I'd see no reason not to keep this true, the libraryURL doesn't exist on a new installation and needs to be created.
> 
> Is it supposed to be created elsewhere perhaps?
> 
No, this is the right place. Thanks for the detailed bug report, I’ve just committed a fix for it.

Yours,
dillo

**Comment by ecstaticax** [comment]
Hi, when will be released an ipa for the latest fixed version? Thanks!

**Comment by dillof** [comment]
Just released version 1.4 which contains the fix.
